name: Release kiki binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        with:
          branch: main
          title: $tag
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            build-tool: cargo-zigbuild
          - target: x86_64-unknown-linux-musl
            build-tool: cargo-zigbuild
          - target: aarch64-unknown-linux-gnu
            build-tool: cargo-zigbuild
          - target: aarch64-unknown-linux-musl
            build-tool: cargo-zigbuild
          - target: armv7-unknown-linux-gnueabihf
            build-tool: cargo-zigbuild
          - target: armv7-unknown-linux-musleabihf
            build-tool: cargo-zigbuild
    name: ${{ matrix.target }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build and upload release asset
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: kiki
          target: ${{ matrix.target }}
          build-tool: ${{ matrix.build-tool }}
          archive: $bin-$tag-$target
          tar: unix
          zip: none
          locked: true
          checksum: sha256
          token: ${{ secrets.GITHUB_TOKEN }}
